name: Example workflow for Python using Snyk 
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install python
      uses: actions/setup-python@v5
      with:
          # Semantic version range syntax or exact version of a Python version
        python-version: '3.8'
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --file=Pipfile
        command: test
